---
# GitHub useweecologyrname or organization and repo name
repo: swood-ecology/soils-data

# Email address and user name that you want to associate with the automated deploys
# Generally you want these to be different from your user account so it is clear
# which commits are automated.
deploy_email: "stephenawood@gmail.com"
deploy_username: "Soils Data Bot"
---
